Repository MicrosoftDocs/azure-monitor-docs, pull requests merged in 2025-07, with the labels that each got.

#173 Update kubernetes-monitoring-firewall.md
  articles/azure-monitor/containers/kubernetes-monitoring-firewall.md
Labels: aq-pr-triaged, do-not-merge, review-team-triage

#166 remove container_memory_usage_bytes metric from default collection
  articles/azure-monitor/containers/prometheus-metrics-scrape-default.md
Labels: aq-pr-triaged, do-not-merge, Change sent to author, azure-monitor/svc, containers/subsvc

#174 Update java-spring-boot.md
  articles/azure-monitor/app/java-spring-boot.md
Labels: do-not-merge, review-team-triage
